### ISSUE TITLE
Release should include a binary distribution for linux and macOS

### ISSUE THREAD

**Issue by bzz** [src-d/go-siva#16]
In order to be easy to install and use `siva`, we should provide a precompiled version of it, for linux and osx.

This is a mirror of src-d/enry#74

**Comment by smola** [comment]
This should be fixed by https://github.com/src-d/go-siva/pull/17 + tag.

**Comment by bzz** [comment]
Nice! So `make packages` builds things for multiple platforms?

What's the advised way to install go-siva?

**Comment by smola** [comment]
@bzz Yes, releases will look the same as in `src-d/borges`: https://github.com/src-d/borges/releases
