### ISSUE TITLE
Glob is slow

### ISSUE THREAD

**Issue by ajnavarro** [src-d/go-siva#42]
It takes too much time to get files from a Glob pattern. Some pprof output here using go-git References() method:

![siva-iterating-references](https://user-images.githubusercontent.com/1196465/54197709-f4a14800-44c4-11e9-9212-ae4c191c9310.png)

**Comment by creachadair** [comment]
Stat operations are expensive. Is the match in this case happening on a single directory, or is it scanning multiple directories? I ask because this pattern is consistent with a single directory having a very large number of direct children.

**Comment by ajnavarro** [comment]
The problem is actually here: https://github.com/src-d/go-billy-siva/blob/master/filesystem.go#L360

It is using glob to list all files inside the siva file.

**Comment by kuba--** [comment]
So, if the performance issue is in the line `siva.Index(index).Glob(fmt.Sprintf("%s*", dir))`
Can we just try to `walk` and collect all filenames where name `startsWith`?

**Comment by jfontan** [comment]
The list of files is lexicographically ordered. I was thinking of using binary search to find the first item with that prefix and stop iterating the list when an item without that prefix is reached. Binary search is used already to find files in the list.
